### ISSUE TITLE
Calculating target location from GeoPose

### ISSUE THREAD

**Issue by rjksmith** [opengeospatial/GeoPose#12]
**Question**: Is target location within the scope of GeoPose? And if so, how can observed objects be properly discriminated?

GeoPose can describe the location and orientation of an observer, but the locations of objects observed may also be of interest. A single GeoPose may align with multiple targets, so how can the intended target be identified correctly? Are we looking at this object in front of us, that object on the horizon, that aircraft, that satellite or that star?

**Below/Above Horizon Use Cases**

If the observer is looking _down_ (below the horizon), then the GeoPose intersects with the ground which allows a target location to be calculated. This may be the intended target location for a camera use case, though may be misleading for other use cases such as the GeoPose of the Sun at night.

If the observer is looking _up_ (above the horizon), then the GeoPose does not intersect with the ground so the target location is undefined. Use cases which observe aerial objects from the ground may wish to calculate the location of (say) an aircraft which is not possible from just location and orientation information as a model aircraft may be confused with a passenger plane.

Adding a _range_ parameter that defines the _distance between the observer and the target_ would address this issue for above and below horizon use cases. This would also address the [two-dimensional use case](https://github.com/opengeospatial/GeoPose/issues/6) in which the problem is particularly acute.

**MISB Video Use Case**

[Motion Imagery Standards Board (MISB)](https://www.gwg.nga.mil/misb/st_pubs.html) allows many target locations to be identified within a single video frame including the frame centre latitude and longitude and corner offset locations - see [MISB 0601, table 1](https://www.gwg.nga.mil/misb/docs/standards/ST0601.16a.pdf) for frame information and [MISB 0903, table 2](https://www.gwg.nga.mil/misb/docs/standards/ST0903.4.pdf) for target details.

**Comment by 3DXScape** [comment]
My opinion is that this case is covered and a valid use of the Advanced GeoPose.

1. Target locations are defined in a local space with origin at the observer. The form and also the Advanced GeoPose concrete data object are able to express this relationship as they currently are defined.
1. A target location (using an Advanced GeoPose) can be located in the coordinate system of the Inner Frame. One of the coordinate axes can be aligned with the ray from the observer to the target and the coordinate value for that axis will be range.

**Comment by rjksmith** [comment]
@3DXScape I agree that a suitable choice of co-ordinate system to align with the look-angle allows range to be calculated.

My question was whether range should be added (optionally) as a seventh degree of freedom in GeoPose or whether this is out of scope. I read your answer to be the latter option though this use case may be worth highlighting in the documentation.

Thanks for your feedback. Hope this helps.

**Comment by 3DXScape** [comment]
I think that targets are an important application of geopose. I think it is in scope but My opinion is that range is covered well enough for V1 because

1. an implementer may add a optional "range" field with all but the strict quaternion GeoPose
2. a reference frame aligned with the target will provide the range in one of the coordinates

**Comment by 3DXScape** [comment]
I meant "my" not "My", of course.

Also related, I think that the Graph structure is a good way to represent a group of targets located relative to a sensor platform. This would also be a way to represent the four "corners" of a view frustum. Some toy implementations would help validate these ideas and would help implementers in this application area in the Users Guide.

**Comment by 3DXScape** [comment]
I have asked for additional information from people who might know:

Context:
1.	A pose is a location and orientation.
2. 	A GeoPose is a pose that can be related to a planetary coordinate system
3. 	Suppose an aerial vehicle has a gimballed camera and a radiation sensor with a response that is a single lobe pointed in a single fixed direction (usually down in the vehicle reference frame) fixed with respect to the body of the vehicle. 
4. 	The vehicle's location and orientation with respect to an Earth frame is known: therefore the vehicle has a GeoPose.
5. 	The camera has a pose related to the vehicle pose and thereby also has a GeoPose.
6. 	The sensor response function gives it a direction so it has a pose within the vehicle frame and thereby also has a GeoPose,
7. 	The nadir point of the vehicle can also be represented as a GeoPose.
8. 	The closest point to the vehicle on the ground can also be represented as a GeoPose.
9. 	Other objects of interest in the air and on the ground have GeoPoses in the vehicle and sensor frames.
10.  The vehicle (or camera or radiation sensor) could give the targets precomputed GeoPoses of itself, for example to facilitate communications via a narrow beam or to facilitate observation of the vehicle without the targets having a search capability. 

**Question**: _[We call the objects in 9) “_targets_” as in “_camera target_” or "_radiation sensor target_” – is target the best name?]_

**Question**: _[What should we call the GeoPose of the vehicle when it is a target of one of its targets? This is a “look for me here” piece of information for a target to “see” or signal the vehicle. Suggestions are "_[retro-pose, reverse pose, and inverse pose[or GeoPose]]_" as in "The retro-pose of the camera aimed at the rocket is the camera's pose in the rocket's frame." or "The reverse pose of the camera aimed at the rocket is the camera's pose in the rocket's frame." or "The inverse-pose of the camera aimed at the rocket is the camera's pose in the rocket's frame."

Note that one of our core concepts is the frame transformation and the second question relates to the inverse frame transformation.

**Comment by 3DXScape** [comment]
Discussion and agreement to close.
