### ISSUE TITLE
JSON Encoding: Consistency of object for Position & Orientation; Meaningful Yaw, Pitch, Roll names

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/GeoPose#14]
Two issues have been identified with the current JSON encoding as examplified at https://geopose.io/geoposeinfo/index.html

- position uses individual members, while orientation is grouped in a JSON object
- the `x`,`y`, and `z` members of `yprAngles` are ambiguous

Either of the following encodings are proposed to address both of these issues:

**Suggestion A**
```json
{ 
   "position" : { 
      "lat" : 46.8093998701448, 
      "lon" : -71.1903396680617, 
      "h" : 798.879776840
   }, 
   "orientation" : { 
      "yaw" : 280.612,
      "pitch" : 28.7,
      "roll" : 0
   } 
}
```

**Suggestion B**
```json
{
  "lat" : 46.8093998701448, 
  "lon" : -71.1903396680617, 
  "h" : 798.879776840,
  "yaw" : 280.612,
  "pitch" : 28.7, 
  "roll" : 0
}
```

**Comment by 3DXScape** [comment]
My preference is style A. A couple of additional comments:

We have two flavours of orientation specification in the Basic GeoPose group: YPR and quaternions. We need to make that explicit by identifying corresponding two types of orientation. Our previous choice identified the difference by using the object names yprAngles and quaternion.   

```
{
	"position": {
		"lat": 46.8093998701448,
		"lon": -71.1903396680617,
		"h": 798.879776840
	},
	"orientation-ypr": {
		"yaw": 280.612,
		"pitch": 28.7,
		"roll": 0
	}
}
```
and

```
{
	"position": {
		"lon": -122.3,
		"lat": 47.7,
		"h": 11.5
	},
	"orientation-quaternion": {
		"x": 0.2506806983454595,
		"y": -0.13564750578999654,
		"z": 0.45616799932736707,
		"w": -0.8430122763279625
	}
}
```

"quaternion" would be fine as a shorter abbreviation: "q" or "qt" or "quat" but I am not sure if we need to save 6 or 9 characters in the Basic version.

I prefer the term "location" to "position" because to me there is a hint of measurement and uncertainty in the term "position". "location" is where I am and "position" is an estimate based on a measurement of some sort. I can live with "position" if that's the consensus. 

Finally, I really hope we can accept some resolution to this issue this week - maybe doing the personal decision-making before the meeting. We "froze" this once before and I am anxious to freeze it again in order to avoid changes to the normative part of the standard and generation of sample data.

**Comment by jerstlouis** [comment]
Per https://github.com/opengeospatial/ogcapi-common/issues/224#issuecomment-808884920 we should avoid the use of `-` inside JSON schemas.

Suggestions:

A) Using `orientation` both quaternion and YPR angles, but adding `"type" : "YPRAngles"` or `"type" : "Quaternion"`
B) Flat members for everything (I know Jan-Erik expressed a preference for that) -- quaternion could be `qw`, `qx`, `qy,` `qz`
C) `quaternion` (with `x`,`y`,`z`,`w` members) and `yprAngles` (with `yaw`, `pitch`, `roll` members)
D) `orientationQuat` and `orientationYPR`

Either location or position is fine with me.

**Comment by 3DXScape** [comment]
Agree on '-' usage.

Also I thought about this some more and realised that "out of band" that in many use cases there will have been a selection of Basic-Quaternion or Basic-YPR agreed on by producer and consumer. The only question is what to do when you are given some JSON and know it is a GeoPose but are not told which "flavour". I think it is better when the question can be answered by some explicit naming rather than "tasting" the contents to see what's there. Also having groups of members that should or should not appear together makes the JSON-Schema more complex and  less comprehensible at a glance.

I am now leaning toward a structure that would not require the (over)confident developer to do anything more than look at a sample and believe that they understand everything - and be correct. In other words, some "self-documenting" JSON. 

- A) I don't like this because it is creating some extra private data typing 
- B) I started here but now think that separate objects are better because they make the structure self documenting so I prefer C) but could live with D)

If we name the individual YPR angles, then I think the name of the yaw-pitch-roll object could be just "angles" because it is clear what the angles are from the named members within the object.

**Comment by jerstlouis** [comment]
@3DXScape So:

```json
{ 
   "location" : { 
      "lat" : 46.8093998701448, 
      "lon" : -71.1903396680617, 
      "h" : 798.879776840
   }, 
   "angles" : { 
      "yaw" : 280.612,
      "pitch" : 28.7,
      "roll" : 0
   } 
}
```

or

```json
{ 
   "location" : { 
      "lat" : 46.8093998701448, 
      "lon" : -71.1903396680617, 
      "h" : 798.879776840
   }, 
   "quaternion" : { 
      "w" : -0.7454589472048,
      "x" :  -0.1907080597924,
      "y" :  0.6187600826533,
      "z" : , 0.1582951486225
   } 
}
```
?

**Comment by 3DXScape** [comment]
Looks good to me! If no further comments to the contrary tomorrow, I will change the JSON Schema, examples, validator, and solarpose service to match.

**Comment by 3DXScape** [comment]
I changed the validator and solar pose service.

**Comment by 3DXScape** [comment]
Ready to close? I have received one comment that "h" is not really very self-documenting.

**Comment by 3DXScape** [comment]
As discussed in our last meeting. Closed now with no additional comments since 14 May.
