### ISSUE TITLE
How to display height_over_ellipsoid for (non OGC) users

### ISSUE THREAD

**Issue by MikelSalazar** [opengeospatial/GeoPose#22]
Although my proposal of using the term "altitude" instead of the confusing "height" term (to describe "the vertical distance from the surface of the WGS84 ellipsoid") has not yet been accepted, several end-users are having problems understanding the meaning of that particular component of GeoPoses when applied to virtual cameras (asking different versions of "why does it say that I am 100 meters in height? Is my VR avatar a giant stuck on the ground?").

Due to this feedback, I wanted to put on record that, at least for "non-geominded" users, it is necessary to add an option in the UI to change the displayed term to "altitude" or "elevation".

**Comment by lieberjosh** [comment]
Elevation may be a more neutral term.

**Comment by MikelSalazar** [comment]
I believe there is no "neutral" term. Nor that this is not a war between the OGC and all other standardization organizations where one has to pick sides (or, at least, I hope not). Until someone else (re)discovers that main geolocation standards ([W3C Geolocation API](https://w3c.github.io/geolocation-api/#coordinates_interface), [GPS](https://www.gps.gov/technical/ps/2020-SPS-performance-standard.pdf), etc ) use "altitude" for the "vertical distances over a fixed point" and thinks that it might actually be a good idea to be compatible/interoperable with them (instead of perpetuating a misconception dating from the XVIII century), us developers will have to create an additional logical layer to give end-users what they actually understand. :-/

**Comment by 3DXScape** [comment]
Now I am feeling better about using the single letter "h" as a symbol for the precise thing meant in the Basic GeoPoses: the height or elevation or normal distance above or below the WGS 84 ellipsoid. This is measured in a direction normal to the ellipsoid and not precisely vertical since verticality is defined by the earth's gravitational field - a vertical distance from a point to the ellipsoid is not generally the same as the normal/perpendicular distance from that point to the ellipsoid. A weighted string hanging from a point 100km above the earth's surface can intersect the ellipsoid at a point up to 10's of meters away from the geometrically nearest point on the ellipsoid. The latter is the definition of the "h" symbol.
I completely understand the potential for confusion with elevation, depth, altitude, height all in common use for similar concepts. I agree with Mikel that there is no neutral term, mostly because the meaning is influenced or defined by the culture and community that uses it.
Calling it "h" (traditional symbol from geodesy, but our audience is mostly developers - not geodesists) or "smiley face" partially solves the problem of neutrality because we are forced to write down *our* definition for the meaning.

**Comment by MikelSalazar** [comment]
As long as there is no possible confusion and the documentation details why we needed to be not-directly-compatible with the Geolocation systems (so I can point others to it when they inevitably ask), I will abide with any decision.  In fact, "h" would be a great option in terms of data length (and it is similar to the "z" that it is used in Google Maps/Earth).

**Comment by 3DXScape** [comment]
The W3C GeoLocation API specifies
`
8.2 altitude and altitudeAccuracy attributes
The altitude attribute denotes the height of the position, specified in meters above the [WGS84] ellipsoid.
`

I wrote a little web app to compare reported altitude with government vertical control benchmarks using the W3C getCurrentPosition API. The reported altitude on an iPhone 12  appears to actually be a height with respect to the WGS84 geoid 10 m - about 22 meters greater than the ellipsoidal height that W3C specifies here in the Seattle area.  On my Google Pixel Android phone, I get -11 meters, which is close to the correct ellipsoidal height specified by W3C.

I haven't really explored this very much yet but I think it reflects the core of Mikel's comments - possibly in an even more serious way than lack of alignment between standards: implementations appear to be inconsistent.

**Comment by 3DXScape** [comment]
Another W3C GeoLocation API example ([see benchmark Z407 doc](https://github.com/opengeospatial/GeoPose/files/6605848/Benchmark_SE.50th.Pl.and.Lk.Wash.Blvd.SE.pdf)):
Official ellipsoidal height is -2.33. iPhone 12 Pro Max iOS 14.5.1 gives 20 m, Google Pixel 5 Android 11 gives -2 m for this high accuracy benchmark that I visited today

![image](https://user-images.githubusercontent.com/4260590/120960523-df054200-c710-11eb-90ff-a4a8d25a258b.png)

**Comment by cperey** [comment]
Discussed on July 16 and closed with agreement to use "h"
