### ISSUE TITLE
quaternions in object notation

### ISSUE THREAD

**Issue by michaelvogt** [opengeospatial/GeoPose#3]
Reading through the draft, I stumbled over the the ordering of the quaternion values. I've only known [x, y, z, w] so far.
Did you consider to use object notation instead of the array notation to prevent errors when using GeoPose?

**Comment by 3DXScape** [comment]
Based on our discussions, including a few twists and turns, it should be x, y, z, w. Since quaternions are encouraged for the default basic GeoPose and the intent is to be as compact as possible, we decided on an array of 4 numbers, with an implicit ordering. You can find the scalar part (w, here) first or last. In math, computer graphics, and games,  x i + y j + z k + w is most common in computing, in my experience. I think at some point we had a discussion about syncing with the current Wikipedia article.  Anyway, it's worth a quick review in a meeting to confirm that we want x, y, z, w and as an array rather than named individual members q.x, q.y, q.z, q.w. The same choice of array applies to Euler angles so we should be consistent.

**Comment by michaelvogt** [comment]
Yes, [x, y, z, w] is a more natural order in the Web/AR environment. I was told, the order in the current document with the w as the first value is common in the robot environment.

So, whichever order is chosen in the end, there will be confusion about it. Object notation would solve this.
Right, it adds additional characters to transport, but the added safety against misinterpretation might be worth it. 

Yes, I also stumbled over the Euler order, but thought to keep the discussion in a single issue to one topic.

**Comment by rjksmith** [comment]
Labelling the named fields in object notation is better design than relying on their numeric order in an (unlabelled) array.

There is already a precedent for this in GeoPose as _latitude_ and _longitude_ are labelled fields rather than inferring meaning from their order in a two-dimensional array.

**Comment by 3DXScape** [comment]
Updated schemata and instance samples in documents.

**Comment by MikelSalazar** [comment]
The issue with quaternions is that, due to their complex nature (and the famous equation  i^2 = j^2 = k^2 = i*j*k = -1), 99.99% of the time, the four components are going to have a value. And, unlike with Euler angles, quaternions do not have an order of application and all of them are mandatory, so explicitly specifying the components each time means wasting at least 16 characters for no good reason.

**Comment by 3DXScape** [comment]
In 5 March SWG meeting we agreed to use object notation to give us field names for both quaternions and Euler angles with naming as in following examples:

> 

{
  "longitude": -122.3,
  "latitude": 47.7,
  "height": 11.5,
  "quaternion": {
    "x": 0.24935508863486583,
    "y": -0.13561967913187356,
    "z": 0.4581349646468323,
    "w": -0.8423429803661402
  }
}

>
{
  "longitude": -122.3,
  "latitude": 47.7,
  "height": 11.5,
  "eulerAngles": {
    "rotX": -0.5756131639306046,
    "rotY": 0.0,
    "rotZ": 5.2869177931177145
  }
}

The corresponding JSON Schema files are updated in the document to reflect this result.

**Comment by MikelSalazar** [comment]
Excuse me Steve, but can you remove the "rot" prefix for the components of the Euler angles (leaving it just as "x", "y" and "z". In that way, it is less redundant (because the term Euler _angles_, already imply rotation) and it would be possible to directly serialize deserialize to the structures already existing in most 3D engines [1](https://threejs.org/docs/#api/en/math/Euler).

**Comment by rjksmith** [comment]
Naming Euler angles _x_, _y_ and _z_ is prone to misinterpretation as these will be mistaken for co-ordinates as discussed last meeting (5th March).

This nomenclature also demonstrates a misunderstanding of Euler angles as the three rotations are not about the _x_, _y_ and _z_ axes as @3DXScape explained - see [Wikipedia for details](https://en.wikipedia.org/wiki/Euler_angles) or [Wolfram for notational conventions ](https://mathworld.wolfram.com/EulerAngles.html).

**Comment by MikelSalazar** [comment]
But there is no confusion possible when the element is called "eulerAngles". All 3D engines use Euler Angles with X, Y, and Z components (in the same way that they use Quaternions with X, Y, Z and W components for the "i", "j", "k" and "a" components of the mathematical definition). Are you going to force implementers to reencoode the serialization system for every GeoPose? Why don't apply the same rule then for quaternions, then? 

Please see how Euler angle based rotations are implemented in the most common 3D engines:
Threejs: https://threejs.org/docs/#api/en/math/Euler
Unity: https://docs.unity3d.com/ScriptReference/Transform-eulerAngles.html
Unreal: https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/FRotator/Euler/index.html
Blender: https://docs.blender.org/api/blender_python_api_current/mathutils.html?highlight=euler#mathutils.Euler

If something, knowing that implementers are going to use normal conventions (that is, not the mathematical ones defined in Wolfram, but those of the 3D engines), adding the "rot" prefix is going to add more confusion rather than eliminate it.

**Comment by rjksmith** [comment]
I disagree. Including two components with the same _(x, y, z)_ nomenclature that have different meanings - co-ordinates or angles - is open to misinterpretation and is an unwise choice.

3D engines are certainly a valid use case, but they are not the only one and the nomenclature should be clear to all GeoPose users. The [GeoPose specification](https://github.com/opengeospatial/GeoPose/blob/main/standard/pdf/geopose_standard.pdf) offers a helpful suggestion in section 7.3.2:

> **7.3.2. Standardization Target 2: Basic-Euler**
The Basic-Euler GeoPose uses a rotation-only transformation from a WGS-84-referenced local tangent plane east-north-up coordinate system. The rotation is specified with three Euler angles denoting rotation angles about the three LTP-ENU axes. The local (rotated) coordinate system axis order is z, y, x. This is commonly referred to as the yaw, pitch, roll.

_Yaw_, _pitch_ and _roll_ seem clear and unambiguous, or perhaps _heading_, _pitch_ and _roll_ as these are geospatial angles.

**Comment by MikelSalazar** [comment]
> I disagree. Including two components with the same (x, y, z) nomenclature that have different meanings - co-ordinates or angles - is open to misinterpretation and is an unwise choice.
By themselves, yes. With the "eulerAngles" before it... no. 

> Yaw, pitch and roll seem clear and unambiguous, or perhaps heading, pitch and roll as these are geospatial angles.
EXACTLY. And they do not have the problem of having to know if they are measured in radians or degrees  (because roll pitch and yaw are always defined in degrees). The only problem is that they are, technically, another type of rotation system ([aircraft-principled axes](https://en.wikipedia.org/wiki/Aircraft_principal_axes)), But if we could ignore that and use "yaw", "pitch" and  "roll" to describe the components of Euler rotations, it would be the best option (at least, for those poor programmers that will need to debug these things in the future).

**Comment by 3DXScape** [comment]
We need to come to agreement on two questions:

1. unit of measure - degrees or radians
2. naming of rotation angles

Based on the recent discussions, I suggest three choices for question 2 - naming the angles [+ => pro - => con]

1. rotX, rotY, rotZ [+rot clearly indicates rotations about axes axes in the expected order -not in the order rotations should be applied]
2. rotZ, rotY, rotX [+rot clearly indicates rotations about axes +correctly implies the order rotations should be applied -not the convention anywhere else -capital letter axis names imply world coordinates not local/body coordinates]
3. x, y, z [+match CG conventions -names do not suggest rotation]
4. heading/yaw, pitch, roll [+match aircraft terminology -yaw often denotes deviation from heading and not an absolute direction -heading and yaw in navigation measured wrt NED frame]

I hope that the choice we make follows some other standard that we can reference as support.

**Comment by rjksmith** [comment]
@3DXScape That's a great summary.

1. **Units of measurement**
    Quaterion and Euler structures have clearly been included for a reason and it's important to understand the original motivation before choosing between degrees and radians. I suggest this is discussed in the SWG meeting.

1. **Euler angle nomenclature**
An [Euler angle](https://en.wikipedia.org/wiki/Euler_angles) has four attributes - _three angular rotations_ and an _order_ in which these are applied. The GeoPose spec defines this order in section 7.3.2 and the nomenclature should reflect this clearly.

    > **7.3.2. Standardization Target 2: Basic-Euler**
The Basic-Euler GeoPose uses a rotation-only transformation from a WGS-84-referenced local tangent plane east-north-up coordinate system. The rotation is specified with three Euler angles denoting rotation angles about the three LTP-ENU axes. The local (rotated) coordinate system axis order is z, y, x. This is commonly referred to as the yaw, pitch, roll.

    Using _EulerAngleZYX_ nomenclature would remove ambiguity in the rotation order and highlight that the associated _(x, y, z)_ attributes correspond to these angular rotations in this order - cf [three.js Euler  object](https://threejs.org/docs/#api/en/math/Euler).

1. **Geospatial nomenclature**

    Common terms used by geospatial communities include:
      i. [Bearing](https://en.wikipedia.org/wiki/Bearing_(angle)) to measure an angle in _degrees_;
      ii. Nautical or Cardian angles to describe an object's orientation as _yaw, pitch and roll_;
      iii. [Heading](https://en.wikipedia.org/wiki/Heading_(navigation)) as an alternative to _yaw_, though it is important to clearly discriminate between _heading_ and [_course_](https://en.wikipedia.org/wiki/Course_(navigation)) for moving objects.

    GeoPose already uses a convenience API to include Euler angle and quaternion definitions aimed at 3d model use cases, but excludes common geospatial terms which seems like an oversight.

**Comment by 3DXScape** [comment]
Updated proposed resolution from 19 March SWG meeting vote:

- Use degrees as unit of measure.
- Use yaw, pitch, roll 

Consequences

1. Replace use of Euler angles by YawPitchRoll or YPR through the standard
2. Basic-Euler => Basic-YPR

**Comment by MikelSalazar** [comment]
In my opinion, there is value in maintaining Euler angles (in Radians) as an option for implementers... but OK, it is a good compromise between intuitiveness and efficiency.

However, by the same, logic I would not use "YPR" as a name, but call it simply "Angles" (because quaternions do not use angular measurements, but distances within a sphere). In that way, the suffix of the Object matches the name of the property and it is easier to remember:
BasicGeopose**Angles** { "**angles**" :{ "yaw": 0, ""pitch": 0, "roll":0},
BasicGeopose**Quaternion** { "**quaternion**" :{ "x": 0, ""y": 0, "z":0,, "w":1 },

And, if we decide to recover the idea of "proper" Euler angles one day, we can maintain consistency in this way:
BasicGeoposeEuler { "euler": { "x": , "y", "z"}}

**Comment by 3DXScape** [comment]
I think we are ready to close this one.

**Comment by 3DXScape** [comment]
And we still have no additional discussions.
